services:
  postgres:
    image: postgres:14
    container_name: mototrust-postgres
    environment:
      POSTGRES_DB: MotoTrust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mototrust-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mototrust-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mototrust-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mototrust-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=MotoTrust;Username=postgres;Password=postgres;Port=5432
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    networks:
      - mototrust-network
    volumes:
      - .:/app
      - /app/bin
      - /app/obj

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  mototrust-network:
    driver: bridge
